### ISSUE TITLE
Profile Photos Appear Stacked on Top of Each Other

### ISSUE THREAD

**Issue by jkoufopoulos** [presidential-innovation-fellows/pif-website#117]
This happened to me when I tried clicking a filter (e.g., Fellows from 2013).

<img width="1106" alt="screen shot 2016-06-08 at 10 26 26 am" src="https://cloud.githubusercontent.com/assets/3787927/15906807/7d1b8008-2d88-11e6-8075-31ccd75ab2bf.png">

**Comment by neilmartis** [comment]
@jkoufopoulos Hi Justin I checked it up as well its rendering fine,I have checked it in chrome and firefox as well

**Comment by neilmartis** [comment]
@jkoufopoulos I have come across the same issue before

**Comment by s2t2** [comment]
@jkoufopoulos is this still happening? If so, can you share which browser and device you are using?
