### ISSUE TITLE
Modal Pop Up for Expanded Bios Appears Partially Above URL Search Bar

### ISSUE THREAD

**Issue by jkoufopoulos** [presidential-innovation-fellows/pif-website#118]
<img width="1270" alt="screen shot 2016-06-08 at 2 50 18 pm" src="https://cloud.githubusercontent.com/assets/3787927/15906866/bffcce9a-2d88-11e6-88dc-8c74eb26eec6.png">

**Comment by s2t2** [comment]
@jkoufopoulos is this still happening? If so, can you share which browser and device you are using?

**Comment by neilmartis** [comment]
@s2t2 @jkoufopoulos The issue is resolved checked on the mobile device and all browsers
