### ISSUE TITLE
Change "Read Full Article" Link

### ISSUE THREAD

**Issue by s2t2** [presidential-innovation-fellows/pif-website#152]
From today's "PIF Website Changes" discussion:

  + Change link text from "Read full article here" to "Learn more"
  + Change link `href` from medium article to `https://gsablogs.gsa.gov/gsablog/2017/11/30/meet-the-newest-presidential-innovation-fellows-2/`

<img width="803" alt="screen shot 2017-12-19 at 5 21 26 pm" src="https://user-images.githubusercontent.com/1328807/34181661-19f1dd8a-e4e1-11e7-8eec-10ff4a644691.png">

**Comment by ver-kat** [comment]
I would like to fix this.

**Comment by s2t2** [comment]
@ver-kat go for it!

**Comment by ver-kat** [comment]
I made a pull request for this fix

**Comment by s2t2** [comment]
resolved by #170
