### ISSUE TITLE
Revise Homepage Counts

### ISSUE THREAD

**Issue by s2t2** [presidential-innovation-fellows/pif-website#153]
From today's "PIF Website Changes" discussion:

  + Remove all counts except for "122 Fellows" and "28 Agencies"
  + Revise region counts (investigate whether or not this happens automatically, and perhaps spin-off a new issue to automate the updating of these numbers)

<img width="1150" alt="screen shot 2017-12-19 at 5 19 06 pm" src="https://user-images.githubusercontent.com/1328807/34181593-d9fe537a-e4e0-11e7-9545-25bdcf6f5d18.png">

**Comment by s2t2** [comment]
So, the hard-coded totals are easy to update manually, but the image is also hard-coded (png file), and needs to be updated or else its counts will contradict the totals on the right. It looks like @stroupaloop and @bwillman have updated this image in the past, so I'm wondering if they are able to share the file that was used to produce the png image. I'd be happy to update it.

This graphic is also possible to update automatically if I have access to the individual region graphics, which I'm hoping I will find in that source file.

**Comment by s2t2** [comment]
I think I see the source file in the shared PIF google drive...

**Comment by stroupaloop** [comment]
I believe Chris Wong is the one who originally created it. If you can't find the assets I'd ask him!

**Comment by s2t2** [comment]
Thanks @stroupaloop I did find it in the google drive. Sorry for the false alarm, but I appreciate your response!
