### ISSUE TITLE
Update Application Timeframes

### ISSUE THREAD

**Issue by s2t2** [presidential-innovation-fellows/pif-website#155]
From today's "PIF Website Changes" discussion:

New desired content for FAQs Page:

> Q: When can I apply? 
> A: We accept applications twice a year, once in the Spring, and once in the Fall. Please check apply.pif.gov for the current application deadline.

EDIT:

The above text is what appears on the site now. The desired change is to replace "twice a year, once in the Spring, and once in the Fall" with "once per year".

And also it might be nice to make the "apply.pif.gov" text into a hyperlink which also links to that address.

**Comment by ver-kat** [comment]
It appears this has already been fixed?

**Comment by s2t2** [comment]
Hmm. you're right @ver-kat . Looks like a potential oversight on my part in the creation of this issue. I have reached out to ask if we want to change this language, or if it should be something else. Will post here when I hear back.

**Comment by s2t2** [comment]
Ahh updating the issue text now @ver-kat. Did you want to take this one?

**Comment by ver-kat** [comment]
I submitted a pull request.
