### ISSUE TITLE
Landing Page Round 1 Design Audit

### ISSUE THREAD

**Issue by AvivaOskow** [presidential-innovation-fellows/pif-website#377]
@echappen The USWDS automatic text resizing might be on... this might be causing the weird font sizes? I suggest turning that variable off if so we have more consistent control

## Hero area
- [x] "to improve the lives of the American people" should be 40px, looks smaller now (39.4px)
- [x] Change spacing between "Uniting innovators..." and "to improve the lives..." to 16px (looks like maybe 32 now)
- [x] Question for Aileen/Aviva: Hero image is a bit pixelated...is there a higher res or should we switch to higher res photo?

## Below the fold

- [x] "We are agents of change" should be 40px
- [x] Subhead should be 22px
- [x] remove numbers 
- [x] Make body copy for these paragraphs 20px, with 28px leading

## Case studies area:
_(My bad because there were two versions in the file Austin sent, but it should look like this:)_

- [x] Needs correct title styling and card header stylings
- Header should be 40px, first word Bold, second word Light Italic, dark blue then the light blue
- We need to ask for subhead text
- Card header/agency name should be 22 Bold, bg-blue-warm-50v #2672DE
- Read more link should have the little blue circle to the left

<img width="710" alt="Screen Shot 2020-10-25 at 7 51 08 PM" src="https://user-images.githubusercontent.com/21244661/97122342-89d56c80-16fb-11eb-9e72-99b95377d0a2.png">

## Other follow up
- Aviva to share logos with blue overlay for third point
- need real quotes and photo of person
-

**Comment by echappen** [comment]
@AvivaOskow I think the slightly scaled down font sizes for Merriweather might be a [USWDS font normalization](https://designsystem.digital.gov/design-tokens/typesetting/overview/) issue:

<img width="664" alt="Screen Shot 2020-10-26 at 8 57 25 AM" src="https://user-images.githubusercontent.com/4267629/97187561-8a5c1a80-1770-11eb-9f04-bba9f7f6f598.png">

for example, when I set the Merriweather headers to another font like Public Sans, the text becomes the pixel sizes we want. 

I don't believe the theme auto text resizing setting is related to this.  Currently the user font size is set to 100% (16px) which is  the default. I'm unaware of a way to disable the font normalization.

**Comment by AvivaOskow** [comment]
@echappen I think that is the issue I want thinking of! Font normalization, not resizing. What's your opinion on this? We turned it off for civilrights.justice.gov.

**Comment by echappen** [comment]
@AvivaOskow Thanks! I didn't know you could turn that off, but I can check out the civil rights code to see how to their doing it.

**Comment by echappen** [comment]
@AvivaOskow Everything on this page is completed except for the Merriweather font adjustments. I referenced the [Civil Rights codebase](https://github.com/usdoj-crt/crt-portal) but I couldn't figure out how to remove the font normalization.
