### ISSUE TITLE
Who We Are Round 1 Design Audit

### ISSUE THREAD

**Issue by AvivaOskow** [presidential-innovation-fellows/pif-website#380]
## Nav bar and hero

- [x] Add nav bar from landing page to this page (and all pages)
- The nav bar will eat into the space of the hero image, so we need to update the height (smaller than it is now is fine though)
- [x] Remove darker blue diagonal shape from hero image, should match the style of landing page
- @AileenMcGraw-PIF will be choosing the image for this page, once she has Aviva will create the b/w version to be uploaded

### Mock
<img width="699" alt="Screen Shot 2020-10-30 at 12 05 26 PM" src="https://user-images.githubusercontent.com/21244661/97728709-45095700-1aa8-11eb-90e8-a4882c98a644.png">

## Mission section

- [x] Switch light blue background color from behind "Who we are/What we do" paragraphs to the "Our mission" section above (currently it's switched)
- [ ] @AileenMcGraw-PIF we need to choose a photo for the circle, I thought the one in the screenshot above could work?
### Should look like this
<img width="768" alt="Screen Shot 2020-10-30 at 11 56 51 AM" src="https://user-images.githubusercontent.com/21244661/97727648-0921c200-1aa7-11eb-92cc-697ef9f4061c.png">

## Our values section

- [x] Update icons (shared in slack and will put in folder)
<img width="856" alt="Screen Shot 2020-10-28 at 5 07 11 PM" src="https://user-images.githubusercontent.com/21244661/97728927-839f1180-1aa8-11eb-9888-e5f9f680a823.png">

## Quote section
@AileenMcGraw-PIF we need real quote and photo

## CTA section
We are using two different styles for this section on the landing page and here, we should make them consistent (either using the diagonal shape behind the text, or just having the text centered on the photo overlay like on this page). We will make a decision about which and then should adjust all.

**Comment by echappen** [comment]
@AvivaOskow These updates are complete! 

Heads up, a Chrome A11y check flagged blue part of the "Our Values" heading as not having enough color contrast. Should I keep it all-white?

<img width="1008" alt="Screen Shot 2020-11-02 at 1 17 11 PM" src="https://user-images.githubusercontent.com/4267629/97909984-acc0db80-1d0e-11eb-8af9-4a579f93d685.png">

And for the CTA section, I made it so you can easily switch between the two-toned version and the red version for different pages, if that influences your decision. Just have to add `footer_tagline: alt` to the page front-matter to switch it to the red version.
