### ISSUE TITLE
Individual Project Round 1 Design Audit

### ISSUE THREAD

**Issue by AvivaOskow** [presidential-innovation-fellows/pif-website#403]
## Mobile header image

- [x] Ping image to right corner so then mobile view isn't just the blank TV

- [x] Make mobile header area shorter, 130px should be fine

### Currently
<img width="1060" alt="Screen Shot 2020-11-17 at 6 43 32 PM" src="https://user-images.githubusercontent.com/21244661/99464011-1cd18300-2905-11eb-947e-cb9be308d626.png">

### Should be
<img width="675" alt="Screen Shot 2020-11-17 at 7 24 01 PM" src="https://user-images.githubusercontent.com/21244661/99466924-442b4e80-290b-11eb-81cb-3675e9f40efd.png">

--- 

## 'Back to All' and 'Visit agency' buttons

- [x] Change font from 20px to 16px

### Currently
<img width="1276" alt="Screen Shot 2020-11-17 at 6 48 14 PM" src="https://user-images.githubusercontent.com/21244661/99464200-8ce00900-2905-11eb-874d-48e52b11f6d3.png">

### Should be
<img width="827" alt="Screen Shot 2020-11-17 at 6 48 25 PM" src="https://user-images.githubusercontent.com/21244661/99464207-91a4bd00-2905-11eb-92e1-76fd78bd2158.png">

--- 

## Mobile
- [x] Update design to match mobile mockup

### Currently
<img width="1068" alt="Screen Shot 2020-11-17 at 7 26 56 PM" src="https://user-images.githubusercontent.com/21244661/99466818-0f1efc00-290b-11eb-843c-b58179ca571b.png">

### Should be
<img width="675" alt="Screen Shot 2020-11-17 at 7 24 01 PM" src="https://user-images.githubusercontent.com/21244661/99466477-7a1c0300-290a-11eb-9bb4-ff91fcc25536.png">

## Bottom opt-in

- [x] Change to this design
<img width="558" alt="Screen Shot 2020-11-17 at 7 34 40 PM" src="https://user-images.githubusercontent.com/21244661/99467272-0e3a9a00-290c-11eb-8557-30c57fba1186.png">

### Currently
<img width="1402" alt="Screen Shot 2020-11-17 at 7 32 10 PM" src="https://user-images.githubusercontent.com/21244661/99467252-024ed800-290c-11eb-99ec-bedf62ce55ac.png">

**Comment by AvivaOskow** [comment]
# Mobile mockup

![mobile](https://user-images.githubusercontent.com/21244661/99467335-2f9b8600-290c-11eb-8a97-96344eebd582.png)

**Comment by echappen** [comment]
@AvivaOskow These items are complete! [Demo here](https://federalist-f7cff978-bf3d-4aaa-bbff-a77bbfc6d827.app.cloud.gov/preview/presidential-innovation-fellows/pif-website/echappen-design-refresh/).

**Comment by AvivaOskow** [comment]
@echappen awesome, thank you! Are the rest of the changes for mobile clear through this mockup and the sketch file I sent?

**Comment by echappen** [comment]
@AvivaOskow Ah sorry, didn't see the other changes there. How would you handle more than 2 fellow headshots on mobile?

**Comment by AvivaOskow** [comment]
@echappen could they get smaller and then break to two lines? Or would it better for them to just start out smaller? I think @keithpif said there weren't so many that had a whole bunch of PIFs on them, so trying not sure if we should design the most common layout for the outlier.. thoughts?

<img width="540" alt="Screen Shot 2020-11-18 at 12 08 59 PM" src="https://user-images.githubusercontent.com/21244661/99563053-de84a400-2996-11eb-9e97-09bfdf2359bb.png">


<img width="466" alt="Screen Shot 2020-11-18 at 12 07 34 PM" src="https://user-images.githubusercontent.com/21244661/99562965-c0b73f00-2996-11eb-99e8-74504271a12a.png">

**Comment by AvivaOskow** [comment]
Oh also one other thing I noticed on desktop @echappen , the circles for the PIFs photos look like they aren't perfect circles? Looks like it's 72 x 78px?

<img width="1268" alt="Screen Shot 2020-11-18 at 12 12 21 PM" src="https://user-images.githubusercontent.com/21244661/99563596-6a96cb80-2997-11eb-91d8-7791f6685759.png">

<img width="240" alt="Screen Shot 2020-11-18 at 12 12 36 PM" src="https://user-images.githubusercontent.com/21244661/99563619-708cac80-2997-11eb-81a8-c9cd53926526.png">
