### ISSUE TITLE
Need to update js loading priority and actions for Fellows page (isotope.js)

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/pif-website#41]
Slow load times for isotope.js / images that's causing the filtering to not work immediately

**Comment by rossdakin** [comment]
~30 MB of images too. I'll crunch them down.

**Comment by rossdakin** [comment]
Just enabled gzip, which killed about 250kB per page – should help some.

**Comment by s2t2** [comment]
Hi, is this issue still active, or is it close-able?
