### ISSUE TITLE
Content edits: https://presidentialinnovationfellows.gov/agencies/

### ISSUE THREAD

**Issue by Marcia-Simms** [presidential-innovation-fellows/pif-website#532]
The How it Works section should read:

"The 2024 PIF cohort of approximately 35 Fellows will begin in February 2024. Agencies interested in hosting Fellows should complete [this form] by July 30, 2023. PIF will evaluate and interview prospective agency partners in early summer 2023."

Under the "Agency participation criteria" section, the last paragraph number should be changed from "FY23" to "FY 24" national...

Please let me know if this is the proper way to make webpage content change requests in the future. Thank you!

**Comment by jaredbain** [comment]
@Marcia-Simms I updated the verbiage of the paragraphs to resemble 2024. Will there be a new link for [this form] or will it be the same?
