### ISSUE TITLE
Marcia Simms - Update Apply Now page

### ISSUE THREAD

**Issue by Marcia-Simms** [presidential-innovation-fellows/pif-website#564]
TOP NAV:

About Us | Meet the Fellows | Projects | For Agencies | Become a Fellow

Apply to Be a 2024 Fellow 
Thank you for your interest in becoming a Presidential Innovation Fellow! Applications for the 2024 fellowship class will be opening soon.

Sign up for updates (this should link to GovDelivery)

About the Fellowship

Presidential Innovation Fellows are mid-to-senior career technologists, designers, entrepreneurs, and strategists.

Each fellow is paired with a federal agency to complete a 12-24 month project as an entrepreneur-in-residence. Learn more about projects that have been completed by past fellows and the values that guide our work.

As a fellow, you’ll gain executive-level exposure in a federal agency. Behind the walls of government, you’ll tackle some of our nation’s biggest challenges.

Making government work better for the people we serve is our top priority. And you have the experience we need to drive that mission home. Together, we can have an incredible impact on how the government delivers to the public at every interaction, each and every time.

After you complete your fellowship, you’ll join our alumni community of more than 250 technologists and innovators in advancing mission-driven solutions at local, national, and international levels.

Requirements
To be eligible for the Presidential Innovation Fellows program, you must be a United States citizen or a resident of American Samoa or Swains Island.

Additionally, fellows must be based in Washington, D.C. for the duration of the fellowship.

There are no education requirements.

All fellows will be required to complete a Public Trust background investigation.

Expertise
Presidential Innovation Fellows have expertise in one of the following areas:

Data Strategy and AI: Data management, machine learning, data science, or modern statistical and computational methods.
Product: Product development, product management, and/or agile software methodologies.
Design and Experience: User experience (UX), human-centered design, service design, implementation design or customer experience (CX).
Digital Transformation and Strategy: Digital marketing or advertising, healthcare innovation, change management, community outreach and engagement, DEIA (diversity, equity, inclusion, and accessibility), venture capital, accelerators, or incubators; or corporate innovation.
Cloud Infrastructure and Technology Leadership cloud computing, cloud infrastructure, or enterprise-level technology leadership.
To qualify as a fellow, you must also have at least one year of experience in each of the following areas:
Leading vision, direction, roadmap or leading the identification of user needs for a project, product, platform, or service.
Providing project or product leadership.
Using iterative, agile, or data-driven methodologies to achieve organizational or project objectives.
Collaborating with senior or executive stakeholders to achieve organizational or project objectives.
Leading stakeholders through organizational change.
Benefits
All Presidential Innovation Fellows are hired at the GS-15 Step 1 pay grade. Learn more about the GS system that defines federal salaries.

As of January 2023, the GS-15 Step 1 salary for the Washington, D.C. locality is $155,700.

All fellows receive federal employee benefits. This includes medical, vision, and dental insurance, FSA accounts, life insurance, paid leave, and the Thrift Savings Plan (the government version of a 401K) with up to five percent matching.

Get Ready to Apply

Sign up for updates. We’ll send you an email when the application is available. We’ll also send you emails about information sessions we’ll be holding before the application opens and throughout the application window.

As part of your application, you’ll need to submit a federal-style resume. If you don’t already have one, it can take some time to put together. Here are tips on writing a federal resume and an example of what a federal resume might look like.

You’ll also be asked to provide a personal statement (no more than 900 characters) on why you want to become a fellow.

Links to professional portfolios or profiles may be included and are optional.

Selection Timeline
Here is a tentative timeline so you can know what to expect.
May 15 - June 23, 2023: Submit your application.
July 2023 - October 2023: Interviews with the Presidential Innovation Fellows team and potential agencies take place.
November 2023 - December  2023: Final selections and tentative offers will be made. Tentative offers are contingent on the successful completion of a background check.
December 2023 - February 2024: After you accept a tentative offer, our pre-employment process begins – including a background check. Learn more about our process.
February 2024: We welcome a new cohort of fellows.

Update PIF Quote and Image:

"Public service has always been a dream of mine. Seeing the team that the President assembled and the Administration’s mandate for racial justice and equity inspired me to apply to join the PIF program.

Karin Underwood (2022 PIF, detailed to the Executive Office of the President) 

Link to changes in Google doc: https://docs.google.com/document/d/1H2sWI-qw7Axw9cvKH-257F3RgWWLWffEJAEUCfpVb4s/edit#heading=h.1y5zsaeks0cj

**Comment by jaredbain** [comment]
@Marcia-Simms Attach the link to the image you want as the new header here on this issue
