### ISSUE TITLE
Add info sessions to the PIF Apply page

### ISSUE THREAD

**Issue by Marcia-Simms** [presidential-innovation-fellows/pif-website#568]
Add new info sessions in staging to the updated Apply page: https://presidentialinnovationfellows.gov/apply/

Ready to Learn to Learn More? Register for an Information Session!

[Monday, May 8, 2023](https://www.eventbrite.com/e/presidential-innovation-fellows-application-information-session-5823-tickets-622447616577)
12:00 PM PT | 12:00 PM ET

[Wednesday, May 17, 2023](https://www.eventbrite.com/e/presidential-innovation-fellows-application-information-session-51723-tickets-622561637617)
	9:00 AM PT | 12:00 PM ET

[Tuesday, May 23, 2023](https://www.eventbrite.com/e/presidential-innovation-fellows-application-information-session-52323-tickets-622698697567)
9:30 AM PT | 12:30 PM ET

[Friday, June 9, 2023 ](https://www.eventbrite.com/e/622705237127)
	9:00 AM PT | 12:00 PM ET

[Thursday, June 15, 2023](https://www.eventbrite.com/e/presidential-innovation-fellows-application-information-session-61523-tickets-622713893017)
	11:00 AM PT | 2:00 PM ET

Details are here: https://docs.google.com/document/d/1H2sWI-qw7Axw9cvKH-257F3RgWWLWffEJAEUCfpVb4s/edit#bookmark=id.mxadobeczxmb

**Comment by jaredbain** [comment]
Updates have been uploaded to the staging link

**Comment by Marcia-Simms** [comment]
Thanks, Jared. Apologies for the confusion: the box should just say "Register for an Information Session:" with the updated dates. The last thing is to just remove "Ready to Learn More?" and add an ":" instead of an "!" Outside of that, it's perfect!

**Comment by jaredbain** [comment]
No worries, just pushed the update
