### ISSUE TITLE
Case study modals don't trigger in phone view

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/pif-website#6]

**Comment by neilmartis** [comment]
@stroupaloop Hi andrew I have checked it in both Chrome and Firefox and the modal triggers I have attached the screenshot for the same.
![screen shot 2016-06-03 at 1 36 43 am](https://cloud.githubusercontent.com/assets/10228512/15769779/40736022-292c-11e6-8485-f2ce82d54eb2.png)

**Comment by s2t2** [comment]
Hi, is this issue still active, or is it close-able?
