### ISSUE TITLE
update demographic map

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/pif-website#63]

**Comment by stroupaloop** [comment]
Need additional info from @EmilyIanacone @sbabitch @adamsfallen @Erren (regions) to complete. This should be done after they've completed their PIF profiles for the website

**Comment by s2t2** [comment]
Given all of these fellow profiles now specify regions, I recommend we close this issue.

<img width="907" alt="screen shot 2017-12-14 at 1 24 20 pm" src="https://user-images.githubusercontent.com/1328807/34008067-20945cd4-e0d2-11e7-87ac-05ae11b56da2.png">
