### ISSUE TITLE
Update FAQ page content

### ISSUE THREAD

**Issue by Dahianna** [presidential-innovation-fellows/pif-website#696]
Implement the updates in the FAQ section of this doc: https://docs.google.com/document/d/1lGVtw8XO0OIP6nfbsMHwbtpa5X7HC5aL_evYXi-uTR4/edit#heading=h.sjf57bnp7exe

**Comment by Dahianna** [comment]
@jared to create branch and implement updates/edits on FAQ

**Comment by jaredbain** [comment]
Resolved with #701 branch
