### ISSUE TITLE
changes to skills 

### ISSUE THREAD

**Issue by kachok** [presidential-innovation-fellows/pif-website#71]
We should have generic "data" skill, considering all "Open Data" PIFs. I think now "data" translated into "Data Viz" which is too narrow.

Also I know some consider that "Cyber" shouldn't be a skill on pif.gov : ) can we change it to "Cybersecurity"?

cc/ @rjmajma

**Comment by datametrician** [comment]
I think data is too generic. I am a fan of adding data science or analytics as a skill set for analytical pifs like me and data engineering or data architect for the open data PIFs. But, that would mean 3 tags for data related topics, viz analytics and architecture.

**Comment by stroupaloop** [comment]
@kachok regarding "Cyber" on the website it lists it as Cyber Security.

Don't have a resolution on data issue yet, would love more recommendations or a consensus.

**Comment by sbabitch** [comment]
Are you open to thoughts on skills broadly, or just trying to nail down the data and cyber?

**Comment by kachok** [comment]
My primary thoughts are that all "Open Data" PIFs are not exactly "data scientists" or "data viz" people, so something broad that covers that would be better. Plain "data" or "open data" category will be great!

**Comment by stroupaloop** [comment]
@sbabitch open to other skills as long as they align with our core mission and theories of practice (more on this soon)!

@kachok I'm happy renaming Data Viz to Data Science (@datametrician) , but shouldn't all PIFs be data driven and open by design so it's a default whether then an identifier?

**Comment by datametrician** [comment]
I'm really against a data science catch all. Data science in addition to
data viz is fine. Mainly because data viz is a separate skill from front
end and analytics.

On Monday, October 26, 2015, Andrew Stroup <notifications@github.com> wrote:

> @sbabitch <https://github.com/sbabitch> open to other skills as long as
> they align with our core mission and theories of practice (more on this
> soon)!
>
> @kachok <https://github.com/kachok> I'm happy renaming Data Viz to Data
> Science (@datametrician <https://github.com/datametrician>) , but
> shouldn't all PIFs be data driven and open by design so it's a default
> whether then an identifier?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/issues/71#issuecomment-151159274>
> .
>


-- 
Joshua Patterson
Presidential Innovation Fellow

**Comment by stroupaloop** [comment]
Being reviewed by the PIF team based on PIF Day, an update is pending and a consolidation of skills will be updated
