### ISSUE TITLE
embed Medium i-frame into site

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/pif-website#86]
see code here

```
<script async src="https://static.medium.com/embed.js"></script><a class="m-collection" href="https://medium.com/presidential-innovation-fellows">Presidential Innovation Fellows</a>
```

**Comment by s2t2** [comment]
This code produces the following effect: 

<img width="155" alt="screen shot 2017-12-14 at 1 28 25 pm" src="https://user-images.githubusercontent.com/1328807/34008296-dadbd8ce-e0d2-11e7-83f6-01d92351132a.png">

Given the large size and black background color, I'm not sure where this embed best fits on the site. Perhaps in a side-bar or on its own page. 

I searched the web for some customization options, but couldn't find any. If we can find some customization options, this issue would be a great candidate for a PR.
